"""Add new table to register hospital sectors

Revision ID: 7235d0e3939e
Revises: 5332658934f3
Create Date: 2025-04-06 22:36:00.065150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7235d0e3939e'
down_revision = '5332658934f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 