"""Add sectors table

Revision ID: 17b0243dc4d1
Revises: 7235d0e3939e
Create Date: 2025-04-06 22:48:07.771118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b0243dc4d1'
down_revision = '7235d0e3939e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 